### PR TITLE
Added Try Parse to sandbox parameter

### PR DESCRIPTION
**Pull request by Dwarner123**
…ring. This was an issue because I set the parameter to "True" and the code was just checking for "true" all lower case. The error I received was a 501 error and was not clear on what was causing the error.

### CODE REVIEW

**Comment by MichaelAllenClark** [comment]
Thanks, not sure why I made that a string to begin with.  I'll pull in this change here shortly.

**Comment by Dwarner123** [comment]
Thanks. It is a minor change but could save time for users in the future.

**Comment by FairyPactera** [comment]
Hi, Can you update the dll version above 5.0.4?
FuelSDK-CSharp-Dot9\FuelSDK-CSharp\bin\Release\Newtonsoft.Json.dll

**Comment by Jetski5822** [comment]
@FairyPactera I updated it on a PR, but I get the feeling that it might take sometime to make it through as it seems this SDK is no longer maintained. https://github.com/salesforce-marketingcloud/FuelSDK-CSharp/pull/21

**Pull request merged**
