### PR TITLE
Update Newtonsoft version

### PR DESCRIPTION
**Pull request by Jetski5822**
To version 8.0.3

### CODE REVIEW

**Comment by sahuja11** [comment]
Hi @Jetski5822 ,

I believe you reached out to us on Twitter about the same. The MC SDKs were introduced some time back and have been community supported since then because of which there a lot of pending issues and out-of-date dependencies. Now, we're actively trying to improve the state of our SDKs. We'll test/merge your submitted pull requests and we'll also try to fix the listed issues over the next couple of days. Thanks for contributing! And feel free to reach out to me if you find any mission-critical issues.

**Comment by Jetski5822** [comment]
Hey - want me to rebase?

**Comment by amagar088** [comment]
That would be great.

Thanks
Ashok Magar
302-266-2000

**Comment by Jetski5822** [comment]
@amagar088 Done - you can now merge.

**Comment by amagar088** [comment]
Thanks for the effort. Appreciate the contribution in the API

**Pull request merged**
